#!/usr/bin/env node

const { execSync } = require("node:child_process");

function run(cmd) {
  try {
    execSync(cmd, { stdio: "inherit" });
  } catch (err) {
    console.error(`\n Hook failed while running: ${cmd}`);
    process.exit(1);
  }
}

console.log("Type Checking!");
const reactAppDir = "./front-end-biyae";
try {
  execSync("npx tsc --noEmit", { stdio: "inherit", cwd: reactAppDir });
} catch (err) {
  console.error(
    `\n Hook failed while running: npx tsc --noEmit in ${reactAppDir}`,
  );
  process.exit(1);
}
console.log("all types are clean.");

// todo:
// the same thing as everything on the original note too... contain it. keep everything contained to itself. lol.
