#!/usr/bin/env node

const { execSync } = require("node:child_process");


const reactAppDir = "./front-end-biyae";

// run function with file path option. 
function run(cmd, options = {}) {
  try {
    execSync(cmd, { stdio: "inherit", ...options });
  } catch (err) {
    console.error(`\n Hook failed while running: ${cmd}`);
    process.exit(1);
  }
}






// -------------------------------
// -        Start of Logic       -
// -------------------------------

console.log("Type Checking!\n" +
  "    ,-.       _,---._ __  / \\\n" +
  " /  )    .-'       `./ /   \\\n" +
  "(  (   ,'            `/    /|\n" +
  " \\  `-\"             \\'\\   / |\n" +
  "  `.              ,  \\ \\ /  |\n" +
  "   /`.          ,'-`----Y   |\n" +
  "  (            ;        |   '\n" +
  "  |  ,-.    ,-'         |  /\n" +
  "  |  | (   |            | /\n" +
  "  )  |  \\  `.___________|/\n" +
  "  `--'   `--'"
);





console.log("checking typescripting!");
// run function call
run("npx tsc", { cwd: reactAppDir });




console.log("trying again for sanity")
try {
  execSync("npx tsc", { stdio: "inherit", cwd: reactAppDir });
} catch (err) {
  console.error(
    `\n Hook failed while running: npx tsc --noEmit in ${reactAppDir}`,
  );
  process.exit(1);
}




// all checks valid
console.log("all types are clean.");
console.log(
  "$$  $$  $$\n" +
  "    __||__||__||__\n" +
  "   | * * * * * * *|\n" +
  "   |* * * * * * * |\n" +
  "   | * * * * * * *|\n" +
  "   |______________|"
);

// todo:
// the same thing as everything on the original note too... contain it. keep everything contained to itself. lol.
